ppa:
  lutris-team/lutris
  oguzhaninan/stacer
alternatives:
  java
  python
  pip
  x-www-browser
sh_commands:
  update_all
  clear_all
  killwindows
  turnoffpc
  set_mode
sh_login:
  custom_path.sh
gdebi_software:
  - name: discord
    url: https://discordapp.com/api/download?platform=linux&format=deb
  - name: min
    url: https://github.com/minbrowser/min/releases/download/v1.17.1/min_1.17.1_amd64.deb
sh_install:
  https://deno.land/x/install/install.sh
  https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
apt:
  gdebi
  flatpak
  ppa-purge
  wmctrl
  xdotool
  xclip
  nano
  featherpad
  gufw
  clamav
  xz-utils
  unzip
  font-manager
  stacer
  jq
  sed
  sqlitebrowser
  python3.8
  default-jdk
  openjdk-8-jdk
  python
  lua
  python3-pip
  python-pip
  npm
  love
  git
  ffmpeg
  okular
  audacity
  dia
  krita
  transmission
  apt-transport-https
  preload
  wget
  firefox
  putty
  telegram-desktop
  discord
  thunderbird
  neovim
flathub:
  com.github.libresprite.LibreSprite
  com.github.marktext.marktext
  com.spotify.Client
  net.bartkessels.getit
npm:
  npx
  nextron
  nvm
pip:
  pyinstaller
  virtualenv
  jupyterthemes
  neovim
  pyls
  python-language-server
  flake8
  isort
  yapf
  jedi
heavy:
  jupyter-notebook
  retroarch
  spotify-client
  libreoffice
  lutris
  steam
pip_git:
  gyt
